nextcloud/updater

index.php

For problems use Exceptions

---

index.php

The updater server returns an empty string in case no update is available.
Before:
After:

Fix case when no update is available

---

index.php

Add a button to start updater

---

index.php

This adds the authentication code using the "updater.secret" in the config key. It's compatible with the SSO login solution existing in the admin panel.
Fixes https://github.com/nextcloud/updater/issues/13

Add authentication

---

index.php

* show common HTTP phrases instead of cryptic status codes (404, 401, 503, ...)
* add a lot of log output
* add "requestID" to be able to track logs of a single request and log current version
cc @LukasReschke @nickvergessen

Refinements

---

index.php

CURLOPT_FOLLOWLOCATION isn't working when PHP with open_basedir is used
Fixes https://github.com/nextcloud/updater/issues/25

Remove CURLOPT_FOLLOWLOCATION

---

index.php

CURLOPT_FOLLOWLOCATION isn't working when PHP with open_basedir is used
Fixes https://github.com/nextcloud/updater/issues/25
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

[stable10] Remove CURLOPT_FOLLOWLOCATION

---

index.php

CURLOPT_FOLLOWLOCATION isn't working when PHP with open_basedir is used
Fixes https://github.com/nextcloud/updater/issues/25
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

[stable9] Remove CURLOPT_FOLLOWLOCATION

---

index.php
lib/RecursiveDirectoryIteratorWithoutData.php

Don't call `SplFileInfo::isDir()` when the directory is excluded anyway.
Fixes #62

Fix open_basedir violation in ./oc/updater/../../

---

index.php
lib/Updater.php
tests/features/bootstrap/FeatureContext.php
tests/features/cli.feature

This PR adds custom app folders that are within the nextcloud root to the expected files list and ignores them when deleting.
Fix for https://github.com/nextcloud/updater/issues/40

Ignore custom app folders

---

index.php
lib/Updater.php

Refactor recursiveDelete

---

index.php

The updater does not check if the downloaded file could be extracted successfully.
This is bad in case that not enough space is available or quota limits have been reached.
This patch checks explicitly for possible extraction errors and throws an exception in such cases.
(Fixing two typos as well)

Explicitly check if extracting files was successful

---

index.php

Before (the loading icon is already the new one - it was the old gif we had):
After:
Basically introduces SVG images, and updated buttons.

Update the design to our current guidelines

---

index.php
lib/RecursiveDirectoryIteratorWithoutData.php
lib/Updater.php
tests/features/stable13.feature

Improved version of https://github.com/nextcloud/updater/pull/152
Allows to update nextcloud even when there is a folder .well-known. Folder is excluded from backup and delete routine.

Add .well-known as expected folder but exclude from backup/delete.

---

index.php

We could not identify another attack vector here, because the token is still not transferred via GET parameters that maybe leak to some logs.
* replaces the headers to properly open the updater from within the settings without the use of eval()
For https://github.com/nextcloud/server/pull/12677
cc @rullzer

Allow to pass the token via query parameter

---

.drone.yml
lib/UpdateCommand.php
tests/features/cli.feature

* fixes #210
Background:
The `setMaintenanceMode` does `require('config.php');` and thus is loading the config.php into the CLI context, changing the maintenance mode value and then writing the file back. This works fine in the web based UI because there each step (disabling the maintenance mode is a single step) is executed in one request. On the CLI side we do all steps within one single PHP call. That results in following execution:
* fetching new code
* replacing code
* enable maintenance mode
* upgrade
* disable maintenance mode
This sounds not like a problem, but there is one in the disable step. The "upgrade" step updates the config.php outside of the currently running PHP process, but the "disable maintenance mode" just uses the same config.php as when the CLI process was started. …

Fix setting of maintenance mode from within PHP in CLI mode

---

lib/UpdateCommand.php

Fix #261 
1) Have multiple php version installed.
2) Call updater.phar with a non default php binary.
3) See that occ is not called with the same php binary.
This patch will use `PHP_BINARY` for executing occ.

Execute occ with same php version as updater

---

index.php

Wraps the plain response body in a `<details>` tag
Fixes #232

Improve the error display on the web based updater

---

.drone.yml
tests/features/master.feature

Master (which is Nextcloud 22) doesn't support PHP 7.2 any more.
For https://github.com/nextcloud/updater/issues/332

Remove obsolete pipeline php72-master

---

index.php
lib/Updater.php

For https://github.com/nextcloud/updater/issues/281

Disable UI when web updater is disabled in config.php

---

Makefile
index.php
index.web.php

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

Build index.php from lib files through Makefile

---

index.web.php

Fix #265, Close #312
URL generation via PHP do not consider cases where the application URL at a reverse proxy is different from the local URL.
Example:
- Public: home.acme/nextcloud
- Private: 192.168.1.8
A reverse proxy forwards the request internally. As the updater is not installed in a subdirectory, the generated (via PHP) URLs are wrong. nextcloud/server has all the code to generate proper URLs for such cases. However, this code is not available here.
Generating the URLs via JavaScript is simpler as the browser is already visiting the right page.
To configure nginx-proxy to serve an application from a subdirectory for testing:
- VIRTUAL_HOST=server2.internal
- VIRTUAL_PATH=/cloud/
- VIRTUAL_DEST=/

Generate URLs via JavaScript

---

README.md

Closes #503 
Builds on latest README changes from #539. Attempts to add notes useful to those looking to make changes to the Updater or understand its internals and how it fits in with the other pieces.
Also:
- Corrects a couple typos
- Adds some additional relevant config parameters
- Some minor structural tweaks
Lastly:
- Further refinements can be built on this foundation as needed.
- Appropriate bits will eventually make there way into the Nextcloud Admin Manual

docs(README): Expand details for devs/contributors + misc tweaks
