index.php

Implement async JS

---

index.php

Make it fancy! :)

---

index.php

* Introduce version numbers in user interface 
* Fix typos in variable names, add PHPDoc and comments
* Make some steps more robust
* Run update only if new version is available
* CSS cleanup and some proper styling for failed state and text
* Remove unneeded code
* Make response handling more robust
* Add error handling to every step
cc @LukasReschke 
Best to be reviewed on a per commit basis.
Some impressions:

Fix many things (mostly error handling stuff)

---

index.php

* also add button to go back to instance
@LukasReschke Could I ask you to fix that the updater is overwritten? I need to add following:
```patch
diff --git a/index.php b/index.php
index bbb834f..a9fa25d 100644
--- a/index.php
+++ b/index.php
@@ -636,6 +636,8 @@ class Updater {
}
}
+		copy('/Users/morrisjobke/Projects/nextcloud/updater/index.php', __DIR__ . '/index.php');
+
$state = rmdir($storageLocation);
if($state === false) {
throw new \Exception('Could not rmdir $storagelocation');
```

Ask for maintenance mode state

---

index.php

Shows a warning before closing the page if the update is in progress. If the update is done or not yet started no warning will be shown.

Show warning before closing page

---

index.php

* Fix variable naming for step states
* Show correct status when resuming update
* Remove unneeded code
* Proper layout for authentication screen 
* Handle resume of update step correct 
@LukasReschke I noticed this while testing :)

Fix issues

---

index.php

For daily builds and other channels.
Requires https://github.com/nextcloud/server/pull/227, otherwise only stable will be used as channel 🙈 

Read channel and build time

---

index.php

Show URL of to be downloaded archive

---

index.php

Makes Scrutinizer a bit happier

Remove redundant code and add definition

---

.drone.yml
Makefile
tests/features/bootstrap/FeatureContext.php
tests/features/master.feature
tests/features/stable10.feature
tests/features/stable9.feature

Tests, tests, tests, tests, tests, tests, tests, tests, ... for most of our tar balls.
cc @rullzer @LukasReschke

Provide integration tests for nearly all scenarios

---

index.php
lib/Updater.php

Adjust updater URL to match the one of the server

---

tests/features/stable10.feature
tests/features/stable9.feature

This tests some common upgrade paths (sadly without much data, but at least it tests if it properly executes the stuff)
cc @jospoortvliet @karlitschek @LukasReschke

test maintenance prereleases

---

index.php

Signed-off-by: Lukas Reschke <lukas@statuscode.ch>
cc @rullzer

[stable10] Adjust updater URL to match the one of the server

---

LICENSE

add AGPL license file

---

index.php
lib/Updater.php

Fixes https://github.com/nextcloud/updater/issues/95
Signed-off-by: Lukas Reschke <lukas@statuscode.ch>

Sanitize version parts received from update server

---

index.php
lib/Updater.php

Basically the same as https://github.com/nextcloud/server/pull/5016 but at the end of an update

Invalidate opcache after update

---

index.php
lib/Updater.php

[stable12] Invalidate opcache after update

---

index.php
lib/Updater.php

Added Proxy

---

index.php

Improve design of updater

---

tests/features/bootstrap/FeatureContext.php
tests/features/cli.feature

Port fixes in tests to master

---

index.php
lib/Updater.php

Third try. I changed the indentation and removed the whitespace. Hopefully the sign-off is good now too...
Everything else is like in commit #180 
@MorrisJobke @danielkesselberg (Sorry for this new commit...)
Signed-off-by: Georg Großmann <georg.grossmann@fau.de>

Make updater handle symlinks correct.

---

index.php
lib/Updater.php

fixes nextcloud/server#6117
this generates a link to the changelog like nextcloud.com/changelog/#X-X-X and adds it to the updater
Signed-off-by: Jonas Sulzer <jonas@violoncello.ch>

add a changelog link to the updater

---

.drone.yml
lib/UpdateCommand.php
tests/features/cli.feature
tests/features/master.feature
tests/features/stable13.feature

[stable14] Fix setting of maintenance mode from within PHP in CLI mode

---

index.php
lib/Updater.php

Thanks to @jospoortvliet for pointing this out.

Fix updater URL

---

index.php
lib/Updater.php

Properly check only for downloaded archive

---

index.php
lib/Updater.php

Followup to #306  for #304 
cc @kesselb

Do not depend on the order of files in a folder

---

.drone.yml
Makefile

Followup to #339, #340, #341, #342

Update used version of box

---

index.php

That would allow to mess up the instance and is only recoverable from CLI.
If CLI usage is wanted then the updater can also be run from CLI.
Before there were two buttons (to keep maintenance mode active) and after that the done step had a button "redirect to updater". This is now done automatically.

Do not allow to keep maintenance mode active in web updater

---

index.php

follow-up to https://github.com/nextcloud/updater/pull/411
Signed-off-by: szaimen <szaimen@e.mail.de>

add dist folder to index.php as well

---

index.php
lib/RecursiveDirectoryIteratorWithoutData.php

Fix https://github.com/nextcloud/server/issues/33295

Fix error when upgrading on PHP 8.1
